from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("search-page", views.searchpage, name="search-page"), # type: ignore
    path("page-2", views.page2, name="page-2"),
    path("page-3", views.page3, name="page-3"),
    path("page-4", views.page4, name="page-4"),
    path("page-5", views.page5, name="page-5"),
    path("page-6", views.page6, name="page-6"),
    path("page-7", views.page7, name="page-7"),
    path("anime", views.anime, name="anime"),
    path("action", views.action, name="action"),
    path("adventure", views.adventure, name="adventure"),
    path("animated", views.animated, name="animated"),
    path("comedy", views.comedy, name="comedy"),
    path("crime", views.crime, name="crime"),
    path("fantasy", views.fantasy, name="fantasy"),
    path("mystery", views.mystery, name="mystery"),
    path("scifi", views.scifi, name="scifi"),
    path("romance", views.romance, name="romance"),
    path("thriller", views.thriller, name="thriller"),
    path("documentary", views.documentary, name="documentary"),
    path("series", views.series, name="series"),
    path("tvshows", views.tvshows, name="tvshows"),
    path("year", views.year, name="year"),
    path("cookies", views.cookies, name="cookies"),
    path("about-us", views.aboutus, name="about-us"),
    path("privacy-policy", views.privacypolicy, name="privacy-policy"),
    path("terms-conditions", views.termsconditions, name="terms-conditions"),
    path("contact-us", views.contactus, name="contact-us"),
    path("the-idea-of-you-2024", views.theideaofyou2024, name="the-idea-of-you-2024"),
    path("mission-impossible-7-dead-reckoning-part-one-2023", views.missionimpossible7deadreckoningpartone2023, 
         name="mission-impossible-7-dead-reckoning-part-one-2023"),
    path("barbie-2023", views.barbie2023, name="barbie-2023"),
    path("before-sunrise-1995", views.beforesunrise1995, name="before-sunrise-1995"),
    path("before-midnight-2013", views.beforemidnight2013, name="before-midnight-2013"),
    path("before-we-go-2014", views.beforewego2014, name="before-we-go-2014"),
    path("dark", views.dark, name="dark"),
    path("fair-play-2023", views.fairplay2023, name="fair-play-2023"),
    path("500-days-of-summer-2009", views.fivehundreddaysofsummer2009, name="500-days-of-summer-2009"),
    path("burning-betrayal-2023", views.burningbetrayal2023, name="burning-betrayal-2023"),
    path("evil-dead-rise-2023", views.evildeadrise2023, name="evil-dead-rise-2023"),
    path("red-white-and-royal-blue-2023", views.redwhiteandroyalblue2023, name="red-white-and-royal-blue-2023"),
    path("after-everything-2023", views.aftereverything2023, name="after-everything-2023"),
    path("game-of-thrones", views.gameofthrones, name="game-of-thrones"),
]